name: "Max Livingston"
description: ""
markdown: kramdown
url: http://localhost:4000
pygments: true
title: "Max Livingston"

author:
  name: maxlivingston
  email: maxliving@gmail.com
  github: maxliving
  linkedin: maxlivingston
  email_md5:
